<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>BluerCurve.Demo</RootNamespace>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Wayland" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Svg.Controls.Skia.Avalonia" Version="$(SvgSkiaVersion)" />
    <ProjectReference Include="../../src/BluerCurve.Icons/BluerCurve.Icons.csproj" />
    <ProjectReference Include="../../src/BluerCurve.Theme/BluerCurve.Theme.csproj" />
    <ProjectReference Include="../../src/BluerCurve.Theme.ColorPicker/BluerCurve.Theme.ColorPicker.csproj" />
  </ItemGroup>
</Project>
