<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>BluerCurve.Tests</RootNamespace>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Headless.XUnit" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Skia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="$(AvaloniaVersion)" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <ProjectReference Include="../../src/BluerCurve.Icons/BluerCurve.Icons.csproj" />
    <ProjectReference Include="../../src/BluerCurve.Theme/BluerCurve.Theme.csproj" />
    <ProjectReference Include="../../src/BluerCurve.Theme.ColorPicker/BluerCurve.Theme.ColorPicker.csproj" />
    <ProjectReference Include="../../samples/BluerCurve.Demo/BluerCurve.Demo.csproj" />
  </ItemGroup>
</Project>
